stages:
  - build

build:
  stage: build
  image: kvaron/quasar-builder:latest
  tags:
    - k8s
  script:
    - npm ci
    - npm run lint
    - npm run typecheck
    - npm run test:ci
    - npm run build
    - apt-get update && apt-get install -y zip
    - cd dist && zip -r ../kvaron-enhancedgrid-panel.zip . && cd ..
  artifacts:
    paths:
      - kvaron-enhancedgrid-panel.zip
    expire_in: 1 week
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push
