name: Release

on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.

permissions: read-all

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.CHANGELOG_PAT }}

      - uses: grafana/plugin-actions/build-plugin@main
        with:
          token: ${{ secrets.CHANGELOG_PAT }}
          # Uncomment after Grafana approves the plugin for public signing
          # policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          attestation: true
          create_release: true
          use_changelog_generator: true
